-- R_GROUP_T 테이블에 ICON_NAME 컬럼 추가
ALTER TABLE R_GROUP_T ADD COLUMN ICON_NAME VARCHAR(10) DEFAULT '📁' COMMENT '그룹 아이콘 (이모지)';

-- 기존 그룹들에 기본 아이콘 설정
UPDATE R_GROUP_T SET ICON_NAME = '📁' WHERE ICON_NAME IS NULL;
