-- ====================================================
-- 이력 관리 시스템 DB 마이그레이션
-- 실행 대상: MariaDB 192.168.3.114:3306
-- ====================================================

-- 1. 신규 테이블: R_ACTIVITY_LOG_T (로그인 세션별 활동 로그)
CREATE TABLE IF NOT EXISTS R_ACTIVITY_LOG_T (
  LOG_ID          BIGINT AUTO_INCREMENT PRIMARY KEY,
  HISTORY_ID      BIGINT,                          -- FK: R_LOGIN_HISTORY_T.HISTORY_ID
  USER_ID         BIGINT NOT NULL,
  ACTION_TYPE     VARCHAR(20) NOT NULL,            -- PAGE_VIEW, CREATE, UPDATE, DELETE
  TARGET_TYPE     VARCHAR(50),                     -- DEVICE, GROUP, MODEL, NOTICE 등
  TARGET_ID       VARCHAR(100),
  TARGET_NAME     VARCHAR(200),
  PAGE_CODE       VARCHAR(50),
  REQUEST_METHOD  VARCHAR(10),
  REQUEST_URI     VARCHAR(500),
  IP_ADDRESS      VARCHAR(45),
  DETAIL          TEXT,
  CREATED_AT      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX IDX_AL_USER (USER_ID),
  INDEX IDX_AL_ACTION (ACTION_TYPE),
  INDEX IDX_AL_CREATED (CREATED_AT),
  INDEX IDX_AL_TARGET (TARGET_TYPE, TARGET_ID),
  INDEX IDX_AL_HISTORY (HISTORY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. R_LOGIN_HISTORY_T에 LOGOUT_AT 추가
ALTER TABLE R_LOGIN_HISTORY_T ADD COLUMN LOGOUT_AT DATETIME DEFAULT NULL;

-- 3. R_PAGE_T 시드 데이터
INSERT INTO R_PAGE_T (PAGE_CODE, PAGE_NAME, PAGE_GROUP, SORT_ORDER, PAGE_PATH) VALUES
  ('login_history', '로그인 이력', 'history', 1, '/history/login');

-- 4. SSH 이력을 이력 관리 그룹으로 이동
UPDATE R_PAGE_T SET PAGE_GROUP='history', SORT_ORDER=3, PAGE_PATH='/history/ssh-sessions'
WHERE PAGE_CODE='ssh_sessions';

-- 5. 기존 사용자에게 새 페이지 VIEW 권한 부여
INSERT INTO R_USER_PAGE_ACCESS_T (USER_ID, PAGE_CODE, CAN_VIEW, CAN_EDIT)
SELECT u.USER_ID, 'login_history', 1, 0 FROM R_USER_T u;

-- 6. 관리자(USER_ID=18)에게 EDIT 권한 부여
UPDATE R_USER_PAGE_ACCESS_T SET CAN_EDIT=1 WHERE USER_ID=18 AND PAGE_CODE='login_history';
